name: Publish to GitHub Pages

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.7.0'
      - name: Setup pnpm
        run: npm i -g pnpm
      - name: Prepare cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install packages
        run: pnpm i --store=node_modules/.pnpm-store
      - name: Build site
        run: pnpm run build --prefix site
      - name: Publish site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/__sapper__/export
